apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: catalog-service
build:
  artifacts:
  - image: raulduenas/catalog-service
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base
      env:
        - BP_JVM_VERSION=16.*
deploy:
  helm:
    releases:
      - name: polar-postgres-catalog
        remoteChart: bitnami/postgresql
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_catalog
          image.tag: 13        
  kubectl:
    manifests:
    - k8s/deployment.yml
    - k8s/service.yml
