server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 5s
    threads:
      max: 100
      min-spare: 10

spring:
  profiles.active: 
  - prod
  - test-data
  application: 
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s 
  config.import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      request-connect-timeout: 1000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
      pool-name: polardb-catalog-pool
  jpa:
    hibernate.ddl-auto: validate

management.endpoints.web.exposure.include: refresh

polar:
  greeting : Welcome to the local(2) book catalog!
