server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    threads:
      max: 100
      min-spare: 10

spring:
  profiles.active: 
  - prod
  - test-data
  application: 
    name: catalog-service
  config.import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      request-connect-timeout: 1000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management.endpoints.web.exposure.include: refresh

polar:
  greeting : Welcome to the local book catalog!
